name: Build XCloud Condenser Appimage

on:
  workflow_dispatch:

jobs:
  build-appimage_x64:
    name: Build XCloud Condenser appimage_x64
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: 'xcloud-condenser'

      - name: Run build script
        working-directory: xcloud-condenser/scripts
        run: |
          ./run-podman-build-appimage.sh

      - name: Upload XCloud Condenser Artifact
        uses: actions/upload-artifact@v3
        with:
          name: XCloud Condenser.AppImage
          path: xcloud-condenser/appimage/XCloud Condenser.AppImage
          if-no-files-found: error
          retention-days: 1
